### ISSUE TITLE
Merge or update Schema References

### ISSUE THREAD

**Issue by StefanApfel-Bentley** [iTwin/itwinjs-core#5909]
```[tasklist]
### Tasks
- [x] Merge schema references that does not exists in target
- [x] Update schema reference if the version is compatible
- [x] Throw error if schema references are not compatible
```
